### PR TITLE
WIP sega multi32 model 1,2,3 update

### PR DESCRIPTION
**Pull request by grant2258**
Is compiling fine but there is a problem with vf there is no sound you get sound if you change add a /12 into the v60 must have missed something will look later

### CODE REVIEW

**Comment by arcadez** [comment]
Ah sorry i forgot we need some code to fix the sound in VF IRQ related i think, it's easy to add
in check the commit in mame2003 to see it.

**Comment by grant2258** [comment]
i dropped all the sega drivers from 098 in and added the cpu needed still no sound atm i wonder if they added some watchdog code or something to 98

**Comment by grant2258** [comment]
just checked on on mame098 itself the sound isint working there either. The thing is i cant even remeber what version of the v60 i done for 2003 plus either

**Comment by grant2258** [comment]
ok well looks like the model1,2,3 and sega32 as well as all the the other sega updates are done and vf sound is fixed im just going to test the games before i push anything this is a big set of games i do play especially the system16 and 18

**Comment by arcadez** [comment]
Sorry bigman another wee mistake the sound fix came later.........

0.101u5: R. Belmont fixed missing sound in Virtua Fighter.

But you sorted it so no harm done :)

**Pull request merged**
